Ajout Service Worker
IESN-IG/da pull request #1
Opened 2021-09-30 20:34 UTC by WolfVic

Bonjour,

J'ai ajouté un service worker assez simple pour pouvoir avoir accès au site même hors connexion. 

Je me suis basé sur [https://web.dev/offline-cookbook/#stale-while-revalidate](https://web.dev/offline-cookbook/#stale-while-revalidate) pour la stratégie.
Cela permet d'utiliser le cache en priorité (plus rapide) mais en le mettant à jour s’il y a une connexion internet. Les nouveaux changements seront donc visibles au prochain refresh.

Victor Santelé

2021-10-01 09:11 UTC, Becold requested changes

2021-10-01 09:11 UTC, Becold commented on scripts/app.js
> +      console.log('ServiceWorker registration failed: ', err);
J'utiliserais `console.error` pour que le message s'affiche en rouge dans la console de dev

2021-10-01 09:11 UTC, Becold commented on sw.js
> +var CACHE_NAME = 'IESN_IG_DA';
Sympa ce système de caching

Je mettrais un n° de version dans ce nom de cache : Si jamais on fait une update dans le repo, il faudra invalider le cache qui se trouve sur les clients.

Par exemple : `var CACHE_NAME = 'IESN_IG_DA_v.1.0.0';`

2021-10-01 09:11 UTC, Becold commented on sw.js
> +    event.respondWith(
Je pense qu'on ne devrait cacher que les requêtes GET : 
```javascript
// Let the browser do its default thing for non-GET requests.
if (event.request.method != 'GET') return;
if (event.request.cache === 'only-if-cached' && event.request.mode !== 'same-origin') {
    return;
}
```

2021-10-01 09:11 UTC, Becold commented on sw.js
> +                var fetchPromise = fetch(event.request).then(function(networkResponse) {
A ce niveau-ci, si response n'est pas undefined (c'est à dire que tu as quelque chose qui a été mis en cache), je le retournerai directement.
```javascript 
// Try to get the response from a cache.
if (response)
{
    return response;
}
// If we didn't find a match in the cache, use the network.
else 
{
    var fetchPromise = ...
    return fetchPromise;
}
```

2021-10-01 09:22 UTC, HunteRoi requested changes
Merci pour ta participation à ce projet! Je rajoute @gaetanledocte et @AnneSMAL comme reviewers supplémentaires, puisque je n'ai moi-même pas l'expérience particulière avec ce projet.

Tu trouveras mes quelques commentaires un peu plus bas! Bon travail :smile:

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +        })
Pour éviter de démarrer un callback hell, je recommende d'utiliser l'async/await pattern. Dans cette zone surlignée mais également 19 à 24.

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +    console.log('Service worker is activated!');
[nice to have] j'utiliserais `console.debug` au lieu d'un `console.log` dans ce cas-ci.

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +];
Pas moyen de charger dynamiquement cette liste? Maintenir une liste d'URLs à rentrer dans le cache risque d'être extrèmement fastidieux plus le projet grandira... Je n'ai pas d'alternative qui me vient à l'esprit directement, mais il pourrait être intéressant de réfléchir à générer cette liste différemment.

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +        })
En outre, il n'y a pas de gestion des erreurs dans ton service worker. Échouer silencieusement, ça peut s'avérer embêtant dans le cadre du débuggage de l'application dans le futur. Ne penses-tu pas qu'il serait intéressant d'ajouter quelques informations ci-et-là dans une `catch` ?

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +                    if (networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic' && networkResponse.url.startsWith('http')) {
Concernant la sécurité et le caching, je pense qu'éviter les URLs `http` et forcer ces dernières à commencer par `https` devrait être une obligation. Cependant, je suis conscient que cela serait embêtant pour le développement local...

2021-10-01 09:22 UTC, HunteRoi commented on sw.js
> +                return response || fetchPromise;
quel but as-tu à renvoyer ceci?

2021-10-01 09:24 UTC, HunteRoi commented on sw.js
> +    event.respondWith(
Je ne suis pas sûr de ce que j'avance, mais je crois que l'application ne fait aucune requête sortante. Cependant, il est vrai que bloquer les autres méthodes n'est pas nécessaire selon moi.

2021-10-01 09:35 UTC, gaetanledocte requested changes

2021-10-01 09:35 UTC, gaetanledocte commented on sw.js
> +var CACHE_NAME = 'IESN_IG_DA';
Le nom du fichier mériterait d'être plus explicite.

Au minimum serviceWorker.js, sinon, un nom encore plus descriptif du rôle de ce service worker en particulier : appOfflineServiceWorker.js, etc.

2021-10-01 09:35 UTC, gaetanledocte commented on sw.js
> +var CACHE_NAME = 'IESN_IG_DA';
Ca impliquerait de mettre à jour ce fichier à chaque update, ou presque. 
Peut-être alors trouver un autre système plus global de numéro de version ? 
Ainsi, on sait que l'on incrémente la version à chaque update mais sans rentrer spécifiquement dans ce fichier sw.js à chaque fois.

2021-10-01 09:35 UTC, gaetanledocte commented on sw.js
> +var urlsToCache = [
Pas fan de cette liste qui pourrait devenir compliquée à maintenir ? Peut-être la charger automatiquement ?

2021-10-01 09:38 UTC, gaetanledocte commented
Merci pour ta participation au projet ! 

Merci également aux reviewers pour les précieux commentaires.

Je n'ai pas de connaissance technique sur l'utilisation des services worker, mais review porte donc sur le contexte plus général.

2021-10-01 14:19 UTC, WolfVic commented on sw.js
> +var CACHE_NAME = 'IESN_IG_DA';
Avec la stratégie actuelle, les fichiers se mettent à jour dans le cache à chaque requête. Mais si le fichier est déjà présent dans le cache, on l'envoie sans attendre la requête.
Donc au prochain refresh, on a la dernière version dans le cache.
Je suis parti du principe qu'il y aura peu de grosse mise à jour et que donc ce n'était pas important d'avoir une version de retard pendant 1 visite.

On peut changer de stratégie si vous voulez. 

Dans ma première version, je fonctionnais sur le principe que si j'avais la requête en cache, je l'envoyais, sinon je vais la chercher, la met en cache et l'envoie.
Le problème est que si on met à jour le programme, l'utilisateur ne le verra pas, sauf s'il force la non-utilisation du cache. (et il le fera jamais)

Travailler avec une histoire de version implique de la changer à chaque changement. Ce qui peut être contraignant en effet. 

Personnellement je ne vois pas de manière de modifier le numéro de version sans aller dans le fichier mais je peux me renseigner.

2021-10-01 14:22 UTC, WolfVic commented on sw.js
> +var urlsToCache = [
Je suis d'accord, en soit on en a pas besoin puisque le sw sauvegarde toutes les nouvelles requêtes non présentent dans le cache et donc la liste est faites "automatiquement".

L'inconvéniant si on ne l'a met pas est qu'il faut que l'utilisateur aille 2 fois sur le site pour l'avoir entièrement dans le cache. 1 fois pour installer le service-worker et 1 fois pour mettre le reste des requêtes dans le cache.

Comme dit plus haut, à voir quelle stratégie à adopter et en fonction voir pour générer cette liste seule oui.

2021-10-01 14:23 UTC, WolfVic commented on sw.js
> +];
Je suis d'accord, ça mérite réflexion. On pourrait l'enlever mais l'utilisateur devra aller 2 fois sur le site pour tout avoir en cache. Puisque le SW ajoute les fichiers qu'il ne connait pas dans le cache.

2021-10-01 14:30 UTC, WolfVic commented on sw.js
> +    event.respondWith(
Le site fait appel à fontawesome et google font mais je ne sais pas si c'est utile de les cacher. En soit, on a un fallback niveau font.

Je vais cacher que les requetes GET qui viennent du site

2021-10-01 14:33 UTC, WolfVic commented on sw.js
> +                var fetchPromise = fetch(event.request).then(function(networkResponse) {
On change de stratégie alors. (même si je crois que j'ai mal implémenté celle actuelle je pense)

Si on ne va pas chercher la requête sur le server, on reste bloqué avec la version caché et donc impossible de mettre à jour dans l'état actuel. 

Il faut voir si on modifie la stratégie de cache actuelle ou pas

2021-10-01 14:35 UTC, WolfVic commented on sw.js
> +                return response || fetchPromise;
Normalement, on envoit la réponse caché si elle existe, sinon celle fetché. Mais en pratique ça fonctionne pas. Je viens de voir que j'ai plein d'erreur sur ma version en ligne d'undefined et promise. J'ai repris la méthode sur web.dev mais j'ai pas fait assez de test.

Je vais voir pour corriger et améliorer ça

2021-10-01 14:38 UTC, WolfVic commented on sw.js
> +        })
je suis pour tout passer en async/await! Mais comme tous les services worker que j'ai vu qu'il y en avait pas. Je n'en ai pas fait. 

J'ai été vérifié, et il n'y a pas de raison de pas passer en async/await. Donc let's go, je m'en occupe.

Je vais essayé de mieux gérer les erreurs en même temps.

2021-10-04 18:56 UTC, WolfVic commented
J'ai plus ou moins changer de stratégie, maintenant le site va charger la première ressource qu'il trouve entre le cache et le réseau (donc dans la plupart des cas le cache) 
Mais il va continuer de mettre à jour le cache à chaque nouvelle visite.

Je n'ai pas modifié la liste des fichiers à charger dans le cache à l'installation pour permettre une utilisation offline dès la deuxième visite et parce que je n'ai pas (encore) trouvé d'alternative. Si on ne met pas de liste, il faut 2 visites pour être accessible hors-ligne. 

Je n'ai pas implémenté le changement de version, car normalement il n'y en a pas besoin. Le cache se met à jour seul.
Risque : un changement de nom de fichier ne va pas le remplacer, mais l'ajouter et donc on aura du cache inutile.

J'ai aussi retiré le callback hell.

N'hésitez pas à faire des remarques à nouveau!

2021-10-04 20:50 UTC, HunteRoi requested changes

2021-10-04 20:50 UTC, HunteRoi commented on scripts/app.js
> +      console.log('ServiceWorker registration failed: ', err);
Je pense que c'est une bonne idée de logger l'erreur avec `console.error`. Peux-tu faire les changements indiqués? @WolfVic

2021-10-04 20:50 UTC, HunteRoi commented on serviceWorkerOffline.js
> +        console.error("Not found in cache or network");
Ajoute la variable `error` comme second paramètre à la méthode `console.error` afin de permettre d'avoir accès au stacktrace en cas d'erreur.

2021-10-04 20:50 UTC, HunteRoi commented on serviceWorkerOffline.js
> +        return Promise.reject('Failed to fetch')
Il est plus intéressant de directement `throw error` dans ce cas précis.

2021-10-04 20:50 UTC, HunteRoi commented on serviceWorkerOffline.js
> +    return Promise.reject('Request not cached');
Tu peux tout simplement `throw new Error('Request not cached');` ici.

2021-10-04 20:50 UTC, HunteRoi commented on serviceWorkerOffline.js
> +    // Perform install steps
Ce commentaire n'apporte rien au code

2021-10-05 06:09 UTC, WolfVic commented on serviceWorkerOffline.js
> +        console.error("Not found in cache or network");
Il y a de grande chance que s’il y a une erreur ce soit une `AggregateError` du `Promise.any` mais j'ai rajouté le `error` dans le log quand même

2021-10-05 20:29 UTC, HunteRoi approved these changes

2021-10-06 08:46 UTC, Becold approved these changes

2021-10-06 10:03 UTC, gaetanledocte requested changes

2021-10-06 10:03 UTC, gaetanledocte commented on serviceWorkerOffline.js
> +];
J'ai l'impression que l'on peut tout de même générer cette liste de manière automatique.
La solution pourrait ne pas être très élégante, mais comme le serviceWorker n'a pas accès au DOM d'après ce que j'ai compris, on doit trouver un moyen de passer cette liste à l'initialisation du serviceWorker.
En cherchant 2 minutes, j'ai trouvé une potentielle solution utilisant les query parameters.

Mon idée est de récupérer les fichiers à ajouter depuis le DOM, avant d'initialiser le serviceWorker (fichier app.js) : 

`
const scriptsToCache = Array.from(document.querySelectorAll("script"))
	.filter(script => script.src.startsWith("https://iesn-ig.github.io/da/"))
	.map(script => script.src.replace("https://iesn-ig.github.io", ""))
const stylesToCache = Array.from(document.querySelectorAll("link"))
	.filter(link => link.rel == "stylesheet" && link.href.startsWith("https://iesn-ig.github.io/da/"))
	.map(link => link.href.replace("https://iesn-ig.github.io", ""))
const filesToCache = scriptsToCache.concat(stylesToCache)

console.log(filesToCache)
`

Puis de passer cette liste à l'initialisation du serviceWorker en l'encodant directement dans l'URL avec les query parameters : https://stackoverflow.com/a/44444379

A voir ce que ça donne en pratique, c'est juste une idée pondue en 5 minutes. :)

2021-10-06 10:03 UTC, gaetanledocte commented on scripts/app.js
> +
Un espace inutile en trop ici :)

2021-10-06 18:39 UTC, gaetanledocte commented
@WolfVic Je vois que tu as demandé ma review mais je ne vois pas de changement par rapport à tout à l'heure, mais commentaires sont toujours là. Un oublie de commit ? :)

2021-10-06 18:43 UTC, WolfVic commented
Oups ! Pardon, je n’avais pas vu qu'il y avait eu une nouvelle review, désolé.
Je check le commentaire du coup

2021-10-06 19:40 UTC, vsantele commented on serviceWorkerOffline.js
> +];
À première vue, en rajoutant des paramètres, le service worker se réinstalle à chaque reload... Je vais voir si j'arrive à trouver la raison et arrêter ça. Sinon il faudra creuser ailleurs

2021-10-06 19:51 UTC, gaetanledocte commented on serviceWorkerOffline.js
> +];
Sinon, ne nous prenons pas la tête sur cette histoire : ta contribution est déjà très bien comme ça et je pense que l'on peut dès maintenant la publier en l'état, comme une première version. Des contributions futures pourrons permettre de d'améliorer ce point. En y réfléchissant, je ne pense que l'on va être amené à mettre cette liste à jour très souvent.

Pour la forme, tu peux juste documenter cela dans le code, genre :

`// todo: find a way to automatically retrieve files to cache`
`// at the moment, it is acceptable to let this list hardcoded, see comments on https://github.com/IESN-IG/da/pull/1`

Merci !

2021-10-06 20:02 UTC, vsantele commented on serviceWorkerOffline.js
> +];
je rajoute ça!

2021-10-11 17:15 UTC, HunteRoi approved these changes

2021-10-11 17:19 UTC, HunteRoi commented
On attend ton go @gaetanledocte 😄

2021-10-12 18:54 UTC, gaetanledocte approved these changes

2021-10-13 21:12 UTC, merged